# name: APINATOR Deployment

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: write

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v3

#       - name: Run deploy script
#         run: ./.github/scripts/deploy.sh
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           tag: ${{ github.ref_name }}
#         shell: bash